services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: gestion_medica
    ports:
      - "3306:3306"
    networks:
      - dawi-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dawi-network

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - dawi-network

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - dawi-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dawi-network

  ms-admin:
    build:
      context: .
      dockerfile: ms-admin/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - dawi-network

  ms-auth:
    build:
      context: .
      dockerfile: ms-auth/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - dawi-network

  ms-clinica:
    build:
      context: ./ms-clinica
    ports:
      - "8083:8083"
    networks:
      - dawi-network

  ms-historial:
    build:
      context: ./ms-historial
    ports:
      - "8084:8084"
    networks:
      - dawi-network

  ms-reportes:
    build:
      context: ./ms-reportes
    ports:
      - "8085:8085"
    networks:
      - dawi-network


networks:
  dawi-network:
    driver: bridge